mode: night
device: cuda

sun:
  direction: [ 0.5949, -0.2689,  0.7575]
  up: [0.0111, 0.0470, 0.9988]
  sky_height: 0.8
  near_dist_T: 0.1
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.1, 0.1, 0.2]
    nonsky: [0.16, 0.15, 0.12]
  spotlights:
    headlight_0:
      position:  [0.0, 0.03, 0.0]
      direction: [0.0, 1.0, 20.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.6
      spot_exp: 30
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 100
      specular_strength: 5
      move_with_cam: True


    streetlight_0:
      position:  [-0.18331337, -0.9962141,  0.18176185]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 100
      specular_strength: 5
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'
    
    streetlight_1:
      position:  [0.2766015,  0.05114532, 0.23476076]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 100
      specular_strength: 5
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'

    streetlight_2:
      position:  [0.79841423, 1.0867127,  0.2468378 ]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 100
      specular_strength: 5
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'