mode: night
device: cuda

sun:
  direction:  [0.8543, -0.0338,  0.5187]
  up: [-0.0246, -0.0414,  0.9988]
  sky_height: 0.8
  near_dist_T: 0.1
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.1, 0.1, 0.2]
    nonsky: [0.16, 0.15, 0.12]
  spotlights:
    headlight_0:
      position:  [0.0, 0.03, 0.0]
      direction: [0.0, 1.0, 15.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.5
      spot_exp: 20
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 3
      move_with_cam: True

    streetlight_0:
      position:  [0.69913447, 0.45619977, 0.12294507]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'

    streetlight_1:
      position:  [-0.2610854,  -0.5795245,   0.11747936]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'