mode: sun
device: cuda

sun:
  direction: [0.8826, -0.0316,  0.4691]
  up: [0.0478, -0.0137,  0.9987]
  sky_height: 0.5
  near_dist_T: 0.2
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.1, 0.1, 0.2]
    nonsky: [0.25, 0.25, 0.2]
  spotlights:
    headlight_0:
      position:  [0.02, 0.03, 0.0]
      direction: [0.0, 1.0, 20.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.5
      spot_exp: 30
      near_dist_T: 0.1
      decay_bound: 5
      emission_r: 0.05
      shininess: 30
      move_with_cam: True
    
    headlight_1:
      position:  [-0.02, 0.03, 0.0]
      direction: [0.0, 1.0, 20.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.5
      spot_exp: 30
      near_dist_T: 0.1
      decay_bound: 5
      emission_r: 0.05
      shininess: 30
      move_with_cam: True

    streetlight_0:
      position:  [0.16413888, 0.07383399, 0.09371908]
      direction: [0, 0, -1.0]
      color: [1.0, 0.7, 0.3]
      intensity: 0.5
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 5
      emission_r: 0.1
      shininess: 30
      move_with_cam: False
    
    streetlight_1:
      position:  [-0.68324685,  0.08734435,  0.06266108]
      direction: [0, 0, -1.0]
      color: [1.0, 0.7, 0.3]
      intensity: 0.5
      spot_exp: 2
      near_dist_T: 0.1
      decay_bound: 5
      emission_r: 0.1
      shininess: 30
      move_with_cam: False