mode: night
device: cuda

sun:
  # direction:  [-0.3204, -0.1371,  0.9639]
  direction: [-0.42024636, 0.75431343, 0.50438502]
  up: [0, 0, 1]
  sky_height: 0.8
  near_dist_T: 0.1
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.01, 0.01, 0.01]
    nonsky: [0.18, 0.16, 0.15]
  spotlights:
    headlight_0:
      position:  [0.0, 0.03, 0.0]
      direction: [0.0, 1.0, 15.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.2
      spot_exp: 20
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: True

    streetlight_0:
      position:  [0.5369063,  -0.49936086,  0.8741595]
      direction: [0.0, 1.0, 0.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.5
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'

    streetlight_1:
      position:  [0.5655332, -0.4906469,  0.7916979]
      direction: [0.0, 1.0, 0.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.5
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'