mode: night
device: cuda

sun:
  # direction:  [-0.3204, -0.1371,  0.9639]
  direction: [-0.42024636, 0.75431343, 0.50438502]
  up: [0, 0, 1]
  sky_height: 0.8
  near_dist_T: 0.1
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.3, 0.2, 0.2]
    nonsky: [0.15, 0.15, 0.18]
  spotlights:
    headlight_0:
      position:  [0.0, 0.03, 0.0]
      direction: [0.0, 1.0, 15.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.2
      spot_exp: 20
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 3
      move_with_cam: True

    streetlight_0:
      position:  [-0.14315322, -0.68694663,  0.12]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'

    streetlight_1:
      position:  [-0.13084081,  0.20725054,  0.1280887 ]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'
    
    streetlight_2:
      position:  [-0.12773028,  1.1791545,   0.138914]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.1
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'