mode: night
device: cuda

sun:
  direction: [0.682818,   0.36328664, 0.63386308]
  up: [0, 0, 1]
  sky_height: 0.8
  near_dist_T: 0.1
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.1, 0.1, 0.1]
    nonsky: [0.16, 0.15, 0.15]
  spotlights:
    headlight_0:
      position:  [0.0, 0.03, 0.0]
      direction: [0.0, 1.0, 15.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.2
      spot_exp: 20
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 3
      move_with_cam: True

    streetlight_0:
      position:  [-0.41169465, -0.02638766, 0.17778862]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.03
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'

    streetlight_1:
      position:  [-1.6334994,   1.0624026,  -0.36978188]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.03
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'
    
    streetlight_2:
      position:  [-3.0860202,  2.348878,  -0.9952481]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.03
      spot_exp: 1
      near_dist_T: 0.1
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'