mode: night
device: cuda

sun:
  # direction:  [-0.3204, -0.1371,  0.9639]
  direction: [-0.07508344, -0.05114832, -0.00162191]
  up: [-0.2542, -0.0781,  0.9640]
  sky_height: 0.8
  near_dist_T: 0.1
  sky_shading: [1.0, 1.0, 1.0]

night:
  ambient:
    sky:    [0.25, 0.2, 0.2]
    nonsky: [0.15, 0.15, 0.18]
  spotlights:
    headlight_0:
      position:  [0.0, 0.03, 0.0]
      direction: [0.0, 1.0, 15.0]
      color: [1.0, 1.0, 0.96]
      intensity: 0.3
      spot_exp: 20
      near_dist_T: 0.5
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 5
      move_with_cam: True

    streetlight_0:
      position:  [-0.33219096, -0.08673815,  0.0952699 ]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.03
      spot_exp: 2
      near_dist_T: 0.5
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'

    streetlight_1:
      position:  [ 0.60723066, -0.10107785,  0.3174156 ]
      direction: [0, 0, -1.0]
      color: [1.0, 0.78, 0.5]
      intensity: 0.03
      spot_exp: 2
      near_dist_T: 0.5
      decay_bound: 10
      emission_r: 0.05
      shininess: 300
      specular_strength: 1
      move_with_cam: False
      flare_size: 300
      flare_path: 'assets/flares/1.png'